// 150 pedidos distintos para el tip del día. cada uno apunta a un dato concreto del usuario (el JSON de aiPayload)
// y a un objetivo: hacer crecer la plata, gastar menos o tapar una fuga. la IA elige las cifras de los datos, nunca las inventa.

export type TipGoal = 'crecer' | 'gastar-menos' | 'fuga'
/** el pedido solo se usa si el usuario tiene ese dato (no tiene sentido hablar de objetivos si no cargó ninguno) */
export type TipNeeds = 'objetivos' | 'presupuestos' | 'recurrentes' | 'micro' | 'categorias' | 'ingresos'

export type TipPrompt = { goal: TipGoal; needs?: TipNeeds; prompt: string }

const c = (needs: TipNeeds | undefined, prompt: string): TipPrompt => ({ goal: 'crecer', needs, prompt })
const g = (needs: TipNeeds | undefined, prompt: string): TipPrompt => ({ goal: 'gastar-menos', needs, prompt })
const f = (needs: TipNeeds | undefined, prompt: string): TipPrompt => ({ goal: 'fuga', needs, prompt })

export const TIP_PROMPTS: TipPrompt[] = [
  // ---- crecer: ahorrar más, armar colchón, hacer trabajar la plata (50) ----
  c('ingresos', 'Mirá la tasa de ahorro del mes y decile en una frase cuánto le falta para llegar al 20 % de su ingreso, con la cifra exacta en plata.'),
  c('ingresos', 'Con la capacidad de ahorro mensual, proponé un monto fijo para apartar apenas cobra y explicá cuánto acumularía en 12 meses.'),
  c(undefined, 'Calculá cuántos meses de gastos típicos cubre su capital disponible y decile qué tan lejos o cerca está del colchón de 3 meses.'),
  c('objetivos', 'Elegí el objetivo más atrasado y decile cuánto debería aportar por mes para llegar a la fecha, usando el aporte recomendado.'),
  c('objetivos', 'Elegí el objetivo más cerca de cumplirse y motivalo con lo que le falta en plata y en tiempo.'),
  c('objetivos', 'Si tiene un objetivo de ahorro, sugerile automatizar el aporte el día que cobra y decile cuánto sería por mes.'),
  c(undefined, 'Compará el ingreso con el gasto típico y decile cuánto margen mensual real tiene para ahorrar, en pesos.'),
  c(undefined, 'Decile cuánto sumaría en un año si redondea hacia arriba cada gasto y aparta la diferencia, usando el promedio de microgastos.'),
  c('ingresos', 'Mirá la previsión de fin de mes y, si queda plata, sugerí qué porcentaje mandar a ahorro antes de que se gaste.'),
  c(undefined, 'Hablale del interés compuesto con su propia capacidad de ahorro mensual: cuánto es por año sin contar rendimientos.'),
  c(undefined, 'Si su capital cubre más de 6 meses de gastos, sugerile separar una parte como respaldo y evaluar qué hacer con el resto, sin nombrar productos.'),
  c(undefined, 'Si su capital cubre menos de 1 mes de gastos, decile que el primer paso es un colchón chico y cuánto sería una primera meta realista.'),
  c('objetivos', 'Proponé dividir el objetivo más grande en metas mensuales chicas y decile el monto de cada una.'),
  c('ingresos', 'Mirá en qué porcentaje del ingreso está el ahorro neto del mes y dale un paso concreto para subirlo un punto.'),
  c('ingresos', 'Decile cuánto ahorraría por año si sube su tasa de ahorro actual cinco puntos, con las cifras de su ingreso típico.'),
  c(undefined, 'Sugerile fijar una "fecha de ahorro" mensual y explicá cuánto tiene que apartar para llegar a su capacidad de ahorro.'),
  c('objetivos', 'Si algún objetivo tiene fecha lejana, mostrale cuánto cambia el aporte mensual si lo adelanta tres meses.'),
  c('ingresos', 'Decile cuántos días de ingreso representa lo que ahorró este mes y cómo mejorar esa cifra.'),
  c(undefined, 'Pedile que revise si la plata que no usa en el mes se queda parada en la cuenta de gastos y sugerile separarla.'),
  c(undefined, 'Mirá el capital disponible y decile qué parte conviene dejar líquida para el mes y cuál puede pensar a largo plazo.'),
  c('ingresos', 'Con el ingreso típico y el gasto típico, decile cuánto necesita ahorrar por mes para tener un año de gastos en cinco años.'),
  c('objetivos', 'Mirá el ahorro acumulado en objetivos y decile qué porcentaje de la meta total lleva cubierto.'),
  c(undefined, 'Si el mes viene bien (gasto menor al anterior), sugerile destinar esa diferencia a ahorro antes de que se diluya, con la cifra.'),
  c('ingresos', 'Si el ahorro neto del mes es negativo, decile cuánto debería recortar por semana para volver a cero.'),
  c(undefined, 'Hablale de pagarse primero a sí mismo: usando su capacidad de ahorro, decile cuánto sería por semana.'),
  c('objetivos', 'Sugerile ponerle un nombre y una fecha a un objetivo nuevo, ya que los que tiene suman cierta cifra, y hablá de sumar uno chico.'),
  c(undefined, 'Decile cuánto de su gasto típico es "no negociable" y cuánto es flexible, y qué hacer con el margen que sobra.'),
  c('ingresos', 'Mirá si el ingreso del mes superó al típico y sugerile que lo extra vaya directo a ahorro, con la cifra del excedente.'),
  c('ingresos', 'Si el ingreso del mes quedó por debajo del típico, decile cómo ajustar el gasto de las próximas semanas, con las cifras.'),
  c(undefined, 'Dale un reto de una semana: ahorrar el monto de su ticket promedio de microgastos cada día y cuánto suma al mes.'),
  c('objetivos', 'Si tiene un objetivo de viaje o compra, sugerile abrir un lugar separado para esa plata y decile cuánto debería tener hoy.'),
  c(undefined, 'Explicale en una frase qué significa que su capacidad de ahorro mensual sea la cifra actual y cómo hacerla crecer.'),
  c('ingresos', 'Decile cuánto representa en pesos un 1 % de su ingreso mensual típico y por qué empezar chico funciona.'),
  c(undefined, 'Sugerile revisar cada tres meses cuánto subió su gasto típico respecto al ingreso, usando los dos números.'),
  c('objetivos', 'Mirá el estado de los objetivos y destacá cuál va en camino, felicitándolo con el dato concreto.'),
  c('ingresos', 'Calculá cuánto debería ahorrar por mes para tener lo equivalente a su ingreso de dos meses en un año.'),
  c(undefined, 'Hablale de diversificar riesgos en general (no productos): que no dependa de una sola fuente de plata, con base en su capital.'),
  c('ingresos', 'Si tiene un ingreso extra este mes, sugerile la regla de dividirlo: parte ahorro, parte gusto, con montos.'),
  c(undefined, 'Decile qué pasaría con su capital en 6 meses si mantiene el ahorro neto de este mes, con la cuenta hecha.'),
  c('objetivos', 'Sugerile revisar si el aporte mensual a sus objetivos es realista frente a su capacidad de ahorro, comparando ambas cifras.'),
  c(undefined, 'Pedile que anote cuánto cree que gasta por mes y lo compare con su gasto típico real, mostrando el número.'),
  c('ingresos', 'Mirá la tasa de ahorro y decile en qué rango está (menos de 10 %, 10 a 20 %, más de 20 %) y qué paso sigue.'),
  c(undefined, 'Sugerile usar el día de cobro como recordatorio de ahorro y decile cuánto apartaría con su capacidad actual.'),
  c('objetivos', 'Si tiene objetivo de emergencia, decile cuánto le falta para cubrir tres meses de su gasto típico.'),
  c(undefined, 'Decile cuánto de su capital equivale a días de vida tranquila (capital dividido gasto diario típico).'),
  c('ingresos', 'Hablale de aumentar ingresos además de recortar gastos: con su ingreso típico, cuánto aportaría un 5 % más.'),
  c('objetivos', 'Proponé el método de las dos cuentas para su objetivo principal y decile cuánto tendría que tener a esta altura.'),
  c(undefined, 'Elegí la categoría que más pesa y decile qué pasaría con su ahorro anual si la baja un 10 %, con la cuenta.'),
  c(undefined, 'Sugerile fijar un tope de gasto diario basado en su gasto típico y decile cuánto ahorra por mes si lo respeta.'),
  c('ingresos', 'Decile cuánto de su ingreso se va en gastos fijos y qué porcentaje le queda libre para decidir.'),
  c('objetivos', 'Motivalo con cuánto le falta por cumplir todos sus objetivos juntos y cuántos meses serían con su capacidad actual.'),
  c(undefined, 'Cerrá con un paso chiquito que pueda hacer hoy en menos de dos minutos para que su plata crezca, con una cifra de sus datos.'),

  // ---- gastar menos: recortes concretos y presupuestos (50) ----
  g('categorias', 'Mirá la categoría de mayor gasto del mes y proponé un recorte del 10 % con el ahorro mensual y anual en pesos.'),
  g('presupuestos', 'Elegí el presupuesto más cerca de su límite, decile cuánto le queda por día y qué hacer para no pasarse.'),
  g('presupuestos', 'Si algún presupuesto va a terminar excedido según la proyección, avisale cuánto se pasaría y sugerile un ajuste concreto.'),
  g('presupuestos', 'Si hay un presupuesto con mucho margen, felicitalo y sugerile mover lo que sobra a ahorro, con la cifra.'),
  g('categorias', 'Compará las dos categorías que más pesan y decile cuál es más fácil de recortar y por qué, con porcentajes.'),
  g('categorias', 'Decile qué porcentaje del gasto mensual se va en la categoría principal y sugerile un tope semanal.'),
  g(undefined, 'Mirá la variación de gastos contra el mes anterior: si subieron, decile cuánto y en qué categoría probablemente.'),
  g(undefined, 'Si el gasto del mes va por debajo del anterior, reconocelo con la cifra y sugerile cómo sostenerlo.'),
  g('categorias', 'Proponé una semana de "gasto mínimo" en la categoría más cara y calculá cuánto podría ahorrar.'),
  g('categorias', 'Sugerile revisar la segunda categoría de gasto: muchas veces pasa desapercibida, y decile cuánto es por mes.'),
  g(undefined, 'Explicale la regla de las 48 horas para compras no urgentes y calculá cuánto podría evitar con sus microgastos.'),
  g('presupuestos', 'Sugerile crear un presupuesto solo para la categoría que más se le va de las manos y proponé un monto basado en su promedio.'),
  g('categorias', 'Decile cuánto gasta por día en la categoría de mayor peso y cuánto sería con un recorte del 15 %.'),
  g(undefined, 'Con la previsión de fin de mes, decile cuánto puede gastar por día el resto del mes para cerrar en positivo.'),
  g(undefined, 'Si la previsión de cierre es negativa, avisale con la cifra y sugerile pausar compras grandes hasta ver los pagos fijos.'),
  g('presupuestos', 'Mirá cuántos días faltan para que termine el período de un presupuesto y calculá el gasto diario que le queda.'),
  g('categorias', 'Sugerile cambiar un hábito caro de la categoría principal por una opción más barata, sin cambiar su rutina, con el ahorro.'),
  g(undefined, 'Decile cuánto gastó en el mes por día en promedio y comparalo con su gasto típico diario.'),
  g('categorias', 'Pedile que se pregunte, antes de gastar en la categoría principal, si lo haría pagando el total del mes junto, y mostrale ese total.'),
  g('presupuestos', 'Sugerile bajar un 5 % el presupuesto de la categoría más holgada y decile cuánto es por año.'),
  g(undefined, 'Hablale de gastos hormiga en general y calculá cuánto suman sus microgastos del mes en plata y en porcentaje del ingreso.'),
  g('categorias', 'Marcá la categoría que más creció respecto al mes pasado y sugerile una acción concreta.'),
  g(undefined, 'Sugerile hacer una compra semanal planificada y decile cuánto gasta hoy en la categoría de supermercado o equivalente, si aparece.'),
  g('categorias', 'Elegí una categoría que no sea la principal y desafialo a bajar un 20 % este mes, con el monto exacto a ahorrar.'),
  g(undefined, 'Decile que un gasto chico repetido pesa más que uno grande aislado y mostrale su patrón de microgastos más caro.'),
  g('presupuestos', 'Si no tiene presupuesto en la categoría principal, sugerile crear uno con tope basado en el promedio, con la cifra.'),
  g(undefined, 'Calculá cuánto necesita bajar su gasto diario para llegar a un 20 % de ahorro y decilo en pesos por día.'),
  g('categorias', 'Sugerile revisar los gastos del fin de semana con la categoría de ocio o salidas, si aparece, y decile cuánto pesa.'),
  g(undefined, 'Pedile que elija un día sin gastos esta semana y calculá cuánto equivale al promedio diario de su gasto típico.'),
  g('categorias', 'Decile cuánto le costaría al año mantener el nivel actual de gasto en su categoría principal.'),
  g('presupuestos', 'Mirá todos los presupuestos y decile cuál está más sano y cuál necesita atención hoy, con porcentajes.'),
  g(undefined, 'Si el gasto del mes supera al ingreso, dejale claro el déficit en pesos y el primer lugar donde recortar.'),
  g('categorias', 'Proponé una regla simple para la categoría de mayor gasto: un tope por semana y cuánto sería.'),
  g(undefined, 'Hablale de cuotas y compras financiadas con base en sus pagos recurrentes y decile cuánto comprometen por mes.'),
  g('recurrentes', 'Mirá el total mensual de pagos recurrentes y decile qué porcentaje de su ingreso comprometen antes de gastar un peso.'),
  g('categorias', 'Sugerile comparar precios en la categoría principal una vez por mes y decile cuánto ahorraría con un 8 % menos.'),
  g(undefined, 'Decile cuánto de su gasto del mes fue en compras chicas y qué pasaría si las junta en una sola compra planificada.'),
  g('presupuestos', 'Sugerile revisar el presupuesto semanal si lo tiene y compararlo con lo gastado en lo que va del período.'),
  g('categorias', 'Decile en qué categoría gastó más que su promedio y qué ocurrió esa semana, sugiriendo revisar los movimientos.'),
  g(undefined, 'Proponé congelar un gasto prescindible por 30 días y calculá el ahorro con el promedio de microgastos.'),
  g('categorias', 'Sugerile usar efectivo o una billetera con tope para la categoría que más se le escapa, con el monto sugerido.'),
  g(undefined, 'Mirá la previsión de fin de mes y decile cuánto margen tiene para un gusto sin culpa, con la cifra.'),
  g('presupuestos', 'Felicitalo si cumplió un presupuesto y sugerile subirse el desafío un 5 % el mes que viene.'),
  g('categorias', 'Mostrale cuánto representa por año la categoría principal y preguntale si ese número le cierra.'),
  g(undefined, 'Sugerile una revisión de 5 minutos los domingos de los gastos de la semana y decile cuánto gastó esta semana en promedio.'),
  g('categorias', 'Elegí la categoría con más movimientos y sugerile agrupar compras para reducir la frecuencia, con el dato.'),
  g(undefined, 'Pedile que ponga un tope a las compras impulsivas online y decile cuánto representan sus microgastos del mes.'),
  g('presupuestos', 'Si el uso de un presupuesto supera el 80 %, avisale con cuántos días restantes y cuánto queda disponible por día.'),
  g(undefined, 'Cerrá con una acción concreta para gastar menos hoy, con una cifra tomada de su gasto del mes.'),

  // ---- fugas: suscripciones, recurrentes, microgastos, anomalías (50) ----
  f('recurrentes', 'Decile cuánto suman sus suscripciones por mes y por año, y pedile que revise cuáles usó en los últimos 30 días.'),
  f('recurrentes', 'Mirá el total de pagos recurrentes y sugerile revisar el más caro primero, con el monto.'),
  f('micro', 'Mostrale el patrón de microgastos más caro y decile cuánto suma al año si sigue igual.'),
  f('micro', 'Decile cuántos microgastos llevó este mes y cuánto suman, y sugerile elegir uno para eliminar.'),
  f('micro', 'Calculá el ticket promedio de sus microgastos y cuántas veces por semana se repite el principal patrón.'),
  f('micro', 'Sugerile esperar 24 horas antes de cada compra chica online y decile cuánto representa hoy.'),
  f('recurrentes', 'Si alguna suscripción subió de precio según los datos, avisale cuánto más paga ahora por mes.'),
  f('recurrentes', 'Sugerile revisar si tiene servicios que se superponen (por ejemplo, dos de streaming) con el total mensual de suscripciones.'),
  f('micro', 'Decile cuánto de su ingreso se va en microgastos y compará con el 5 % como referencia.'),
  f('recurrentes', 'Pedile que busque cobros automáticos que no recuerda y decile cuántos pagos recurrentes detectamos.'),
  f('micro', 'Mostrale el comercio donde más veces gasta poco y cuánto suma al mes, para que decida si quiere seguir.'),
  f(undefined, 'Si hay un gasto fuera de lo normal este mes, señalalo y sugerile revisar que sea correcto, con el dato.'),
  f('recurrentes', 'Decile qué porcentaje de su gasto mensual son pagos recurrentes y por qué conviene revisarlos cada tres meses.'),
  f('micro', 'Compará los microgastos del mes con su promedio mensual y decile si va mejor o peor.'),
  f('micro', 'Proponé un tope semanal para el rubro de microgastos que más pesa y calculá el ahorro mensual.'),
  f('recurrentes', 'Sugerile pasar una suscripción anual a mensual o al revés si conviene, y recordale revisar el costo total, con base en su total de suscripciones.'),
  f('micro', 'Hablale del efecto "goteo": muchos gastos de poca plata, y mostrale la suma anual de sus patrones.'),
  f(undefined, 'Pedile que revise sus movimientos de la última semana buscando duplicados o cobros raros.'),
  f('recurrentes', 'Decile cuánto pagó este mes solo en cosas que se renuevan solas y sugerile ponerle una alarma de revisión.'),
  f('micro', 'Si el rubro de delivery o comida pedida aparece entre sus patrones, decile cuánto suma por mes y sugerile reemplazar un pedido por semana.'),
  f('micro', 'Si aparece el café o los snacks entre sus patrones, calculá cuánto son por año y sugerile llevar de casa algunos días.'),
  f('micro', 'Si hay viajes cortos en apps entre sus patrones, decile cuánto suman por mes y sugerile alternativas para los tramos cortos.'),
  f('recurrentes', 'Sugerile ordenar sus pagos recurrentes por monto y cancelar o pausar el que menos valor le da, con el total que liberaría.'),
  f(undefined, 'Calculá qué porcentaje de su gasto del mes es discrecional (microgastos más ocio) y cómo afecta a su ahorro.'),
  f('recurrentes', 'Mostrale cuántos meses de ahorro equivale lo que paga al año en suscripciones.'),
  f('micro', 'Decile qué pasaría con su capital en un año si elimina el 25 % de sus microgastos, con la cuenta.'),
  f(undefined, 'Sugerile revisar los gastos en cuotas y financiaciones, y decile cuánto compromete por mes en pagos recurrentes.'),
  f('micro', 'Hablale de la diferencia entre gasto chico y gasto que no se nota: mostrale su cantidad de microgastos del mes.'),
  f('recurrentes', 'Pedile que revise si alguna suscripción la usa menos de una vez por mes, mostrando el total mensual en juego.'),
  f('micro', 'Si sus microgastos subieron respecto de su promedio, avisale cuánto y sugerile volver al ritmo anterior.'),
  f(undefined, 'Sugerile activar un aviso de gasto grande en su banco y decile cuál fue su mayor categoría este mes.'),
  f('recurrentes', 'Decile cuál es el pago recurrente más grande y qué porcentaje del total mensual representa.'),
  f('micro', 'Proponé un experimento de 14 días sin microgastos en un rubro puntual y calculá el ahorro estimado.'),
  f(undefined, 'Revisá si hay categorías donde el gasto del mes es mucho mayor al típico y señalá la más desviada.'),
  f('recurrentes', 'Sugerile juntar todas sus suscripciones en una fecha para controlarlas mejor y decile cuánto pagan en conjunto.'),
  f('micro', 'Mostrale cuánto gasta en promedio por compra chica y cuántas compras así hace al mes, para dimensionar el goteo.'),
  f(undefined, 'Pedile que revise los cobros del último mes con categoría "otros" o sin categoría, si hay, y decile qué hacer.'),
  f('recurrentes', 'Si el total de pagos recurrentes crece mes a mes, avisale y sugerile ponerle un tope con el monto actual.'),
  f('micro', 'Decile cuánto representa por día sus microgastos y cuánto ahorraría al mes con una pausa de tres días por semana.'),
  f(undefined, 'Hablale de las comisiones y costos escondidos en general y sugerile revisar los pagos recurrentes por monto.'),
  f('micro', 'Sugerile cambiar el medio de pago de compras chicas a uno con tope para no perder noción, y mostrale el total del mes.'),
  f('recurrentes', 'Calculá cuánto ahorra por año si pasa de dos suscripciones de las que detectamos a una sola.'),
  f(undefined, 'Pedile que revise su fuga más grande en Fugas de dinero y decile qué número aparece primero ahí.'),
  f('micro', 'Si el patrón principal de microgastos supera cuatro veces por semana, sugerile un límite semanal con el monto.'),
  f('recurrentes', 'Decile cuánto de su ingreso típico queda comprometido en pagos fijos y por qué conviene mantener ese número bajo.'),
  f(undefined, 'Sugerile revisar los gastos de los últimos tres días buscando un cobro que no reconozca, y mencioná su mayor gasto reciente.'),
  f('micro', 'Mostrale la suma de sus tres patrones de microgastos más caros y qué pasaría si recorta uno solo.'),
  f('recurrentes', 'Si tiene suscripciones, proponé una auditoría mensual de 3 minutos y decile cuánto está en juego.'),
  f(undefined, 'Cerrá con una fuga concreta que pueda tapar hoy, con la cifra mensual y anual tomadas de sus datos.'),
]

/** solo los pedidos que tienen datos para responder */
export function applicablePrompts(has: Record<TipNeeds, boolean>): TipPrompt[] {
  return TIP_PROMPTS.filter((p) => !p.needs || has[p.needs])
}
